### ISSUE TITLE
UI issues on mobile

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/thedatalab#32]
FYI @morleyjr @inglesp here are the issues I came across

1. It's not clear whose site it is because our name/ logo doesn't appear at the top
![image](https://user-images.githubusercontent.com/24392156/94804288-7972f000-03e2-11eb-946d-6754911df985.png)

2. The menu has two `Home`s
![image](https://user-images.githubusercontent.com/24392156/94804344-93acce00-03e2-11eb-88e5-21763bdf1607.png)

3. The topic-specific menu doesn't work well because you can't see all of the items, either horizontally or vertically:
![image](https://user-images.githubusercontent.com/24392156/94804440-b939d780-03e2-11eb-8197-ee3b90ad0129.png)

**Comment by madwort** [comment]
(2) and (3) seem to be fixed on the latest review site, although not (1).

**Comment by morleyjr** [comment]
> (2) and (3) seem to be fixed on the latest review site, although not (1).

1 we decided was a bit of a faff to do and we had previously decided not to put the logo everywhere. So what I am going to do is edit the image that appears on the homepage to put our logo in the corner of it. That will solve the issue.

**Comment by madwort** [comment]
Hmmm, it might be tricky to edit the homepage image, because I think the crop changes as the size of the browser window changes - so there might not be a reliable corner to put it in.

**Comment by morleyjr** [comment]
Oh, good point. Hmm. Maybe I should put the logo in the text description? I think that should be possible.

**Comment by jonny5532** [comment]
I can make it show logo on homepage on mobile as a special case, which probably solves that?

**Comment by morleyjr** [comment]
That would be awesome!

**Comment by jonny5532** [comment]
Here: http://ebmdatalab.s2.sitereview.io/
- I have added the logos to the homepage hero on mobile
- I've also made the logos smaller on mobile

Thoughts?

**Comment by morleyjr** [comment]
Looks great! Thank you so much.
