### ISSUE TITLE
Direct link to team member profiles / bios

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/thedatalab#53]
We host profiles / bios for all team members on a single page https://www.thedatalab.org/about-us/

There is occasion when it is helpful to have a direct link to a team member profile / bio. For example when a single team member has written a blog. The individual profiles used to also rank quite highly in terms of page hits for previous website. Not saying its a good reason to do it but does show that people are clicking on them!

**Comment by madwort** [comment]
looks like it would be straightforward to use [slugify()](https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.text.slugify) to turn "Tom Ward" into "tom-ward" and update [the team template](https://github.com/ebmdatalab/thedatalab/blob/master/thedatalab/frontend/templates/team.html#L10) to add an id (I don't have a local dev setup to test that theory tho...)

**Comment by madwort** [comment]
After discussion with Jonny, I think the plan is to create links from the about us page to the relevant author page.

**Comment by madwort** [comment]
done!
