### ISSUE TITLE
Announce Bennett launch

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/thedatalab#79]
Expected "no later than 20 Sept"

There will be a launch announcement. This will go on the new domain's holding page (currently managed by dept IT; liaise via @BeckyLumbard).

When this exists:
* thedatalab.org needs a copy of the announcement in our blog
* Add "DataLab is becoming the Bennett Institute. Read more here" text to home page, linking to anouncement on the new domain; possibly in a discreet banner?

**Comment by BeckyLumbard** [comment]
FYI press release will include a link to new domain www.bennett.ox.ac.uk → http://072.kairuku.haiku.fry-it.com

**Comment by tomodwyer** [comment]
![bennett-banner](https://user-images.githubusercontent.com/24863179/132831330-6c3681be-c201-4d74-bf76-42fca171745b.png)

OK I've got a PR ready locally - it can be pushed on the 15th.

**Comment by tomodwyer** [comment]
Closed by https://github.com/ebmdatalab/thedatalab/pull/80
